### ISSUE TITLE
Error in TSharc2.h while compiling GRSIData

### ISSUE THREAD

**Issue by akanksha-sing** [GRIFFINCollaboration/GRSIData#124]
I am trying to install GRSIData within GRSISort (v 4.0.0.5). I was able to compile GRSISort with ROOT version 6.28.12, but I am having issues compiling GRSIData in my setup. I am getting the following error: 

```  In file included from libraries/TGRSIAnalysis/TSharc2/TSharc2.cxx:1:
/home/akanksha/Desktop/work/NeutronExperiment/AnalyzingData/Li11Data/GRSISort-4.0.0.5/GRSIData/include/TSharc2.h: In member function ‘int TSharc2::GetSize() const’:
/home/akanksha/Desktop/work/NeutronExperiment/AnalyzingData/Li11Data/GRSISort-4.0.0.5/GRSIData/include/TSharc2.h:49:33: error: ‘Hits’ was not declared in this scope; did you mean ‘fHits’?
   49 |    int GetSize() const { return Hits().size(); }   //!<!
      |                                 ^~~~
      |                                 fHits 
```

**Comment by akanksha-sing** [comment]
This works for me now.

**Comment by VinzenzBildstein** [comment]
I'm assuming that updating GRSISort to the newest version is what made it work for you? Or was it something else?

**Comment by akanksha-sing** [comment]
Hello Vinzenz. I am not sure if that was the problem here since I was using GRSISort version 4.0.0.5, which is the latest version. I have not been able to compile GRSIData when I use the versions of GRSISort+GRSIData from Github, that still does not work for me and I am getting the same error. I had to use the GRSISort folder that came with Li11 experiment data and that compiled perfectly, once I ran make clean and then make in both GRSISort and GRSIData folders, so I am not sure what is happening here.

**Comment by akanksha-sing** [comment]
Hello Vinzenz. I am not sure if that was the problem here since I was using GRSISort version 4.0.0.5, which is the latest version. I have not been able to compile GRSIData when I use the versions of GRSISort+GRSIData from Github, that still does not work for me and I am getting the same error. I had to use the GRSISort folder that came with Li11 experiment data and that compiled perfectly, once I ran make clean and then make in both GRSISort and GRSIData folders, so I am not sure what is happening here.

**Comment by VinzenzBildstein** [comment]
The version numbers of GRSISort only give a very rough idea on how new the code is you are using.
A better check would be the commit you are on in GRSISort and GRSIData. This error you are seeing is because GRSIData is on the newer version which has the data members of the base classes as private and protected setters and getters. If this GRSIData version is compiled against a GRSISort version that does not have this change in the base classes, you will get this kind of error (the compiler complaining that there is no getter function `Hits()` for the `fHits` data member ).
