### ISSUE TITLE
Accessing TIGRESS addback hits causes segfault

### ISSUE THREAD

**Issue by e-j-w** [GRIFFINCollaboration/GRSIData#90]
The latest changes to TTigress.cxx seem to be causing segfaults whenever I call `TTigress::GetAddbackMultiplicity()`.  This is when I'm sorting an analysis tree unpacked using the most recent commits of GRSISort and GRSIData, with an external sort code compiled against the same GRSISort, on CentOS 7.

I believe that this is the same issue that came up in [this](https://github.com/GRIFFINCollaboration/GRSIData/pull/58) previous PR, where deleting the addback hits is causing some weird behavior (which we didn't figure out at the time).  The culprit is commit fcdf3969f0644824790320d07182b8f459b50778 - removing the three lines containing `for(auto& hit : fAddbackHits) delete hit;` from TTigress.cxx seems to fix the issue.  I'll send a PR, but as before, I'm not sure if there's a better solution.

I'm not sure if the same issue occurs for GRIFFIN data.

**Comment by VinzenzBildstein** [comment]
The issue does not occur for TGriffin, which is probably why I added this back in when I changed the ```auto``` to ```auto&```. In fact not deleting them creates a memory leak in TGriffin and TFipps. Anyway, since apparently this is the way it has to be for TTigress, I will add comments to remind me not to put the delete statements back in again, sorry.
